services:
  weatherforecast:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
      - ASPNETCORE_HTTP_PORTS=80  
      - ASPNETCORE_URLS=http://+:80
    ports:               
        - "1116:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  wssoaptranslator:
    image: ${DOCKER_REGISTRY-}wssoaptranslator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=2350
    build:
      context: .
      dockerfile: WsSoapTranslator/Dockerfile
    ports:
        - 1118:2350