services:
  weatherforecast:   
    container_name: WeatherForecastWebClient
    image: ${DOCKER_REGISTRY-}weatherforecast
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "1116:80"  
      

  wssoaptranslator:   
    container_name: WeatherForecastSoapWs
    image: ${DOCKER_REGISTRY-}wssoaptranslator
    build:
      context: .
      dockerfile: WsSoapTranslator/Dockerfile
    ports:
        - 1118:2350

